# Generated by Django 4.2.1 on 2023-05-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HashInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash_name", models.CharField(max_length=20)),
                ("complexity_brut", models.IntegerField(max_length=20)),
                ("edition_year", models.DateField(max_length=20)),
                ("when_used", models.DateTimeField(max_length=20)),
                ("military", models.BooleanField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ImplantInfoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("implant_name", models.CharField(max_length=20)),
                (
                    "buy_possibility",
                    models.CharField(
                        choices=[
                            ("IMPOSSIBLE", "im"),
                            ("DIFFICULT", "df"),
                            ("MIDDLE", "md"),
                            ("EASY", "ez"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "strange_type",
                    models.CharField(
                        choices=[
                            ("IMPOSSIBLE", "im"),
                            ("DIFFICULT", "df"),
                            ("MIDDLE", "md"),
                            ("EASY", "ez"),
                        ],
                        max_length=20,
                    ),
                ),
                ("defense", models.IntegerField(max_length=20)),
            ],
        ),
    ]
