# Generated by Django 4.2.1 on 2023-05-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hashinfomodel',
            name='edition_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hashinfomodel',
            name='military',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='hashinfomodel',
            name='when_used',
            field=models.DateTimeField(),
        ),
    ]
