# Generated by Django 4.2.1 on 2023-05-11 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('time', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('quote_connect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap_soup.authorname')),
            ],
        ),
    ]
